// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_keys.sql

package dbgen

import (
	"context"
)

const getActiveKeyForAgent = `-- name: GetActiveKeyForAgent :one
SELECT id, agent_id, public_key, fingerprint, encrypted_private_key, status, created_at, revoked_at FROM agent_keys
WHERE agent_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveKeyForAgent(ctx context.Context, agentID int64) (AgentKey, error) {
	row := q.db.QueryRow(ctx, getActiveKeyForAgent, agentID)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.EncryptedPrivateKey,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgentKeyByFingerprint = `-- name: GetAgentKeyByFingerprint :one
SELECT id, agent_id, public_key, fingerprint, encrypted_private_key, status, created_at, revoked_at FROM agent_keys WHERE fingerprint = $1
`

func (q *Queries) GetAgentKeyByFingerprint(ctx context.Context, fingerprint string) (AgentKey, error) {
	row := q.db.QueryRow(ctx, getAgentKeyByFingerprint, fingerprint)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.EncryptedPrivateKey,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAgentKey = `-- name: InsertAgentKey :one
INSERT INTO agent_keys (agent_id, public_key, fingerprint, encrypted_private_key)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_id, public_key, fingerprint, encrypted_private_key, status, created_at, revoked_at
`

type InsertAgentKeyParams struct {
	AgentID             int64  `json:"agent_id"`
	PublicKey           []byte `json:"public_key"`
	Fingerprint         string `json:"fingerprint"`
	EncryptedPrivateKey []byte `json:"encrypted_private_key"`
}

func (q *Queries) InsertAgentKey(ctx context.Context, arg InsertAgentKeyParams) (AgentKey, error) {
	row := q.db.QueryRow(ctx, insertAgentKey,
		arg.AgentID,
		arg.PublicKey,
		arg.Fingerprint,
		arg.EncryptedPrivateKey,
	)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.EncryptedPrivateKey,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listKeysForAgent = `-- name: ListKeysForAgent :many
SELECT id, agent_id, public_key, fingerprint, encrypted_private_key, status, created_at, revoked_at FROM agent_keys
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKeysForAgent(ctx context.Context, agentID int64) ([]AgentKey, error) {
	rows, err := q.db.Query(ctx, listKeysForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentKey{}
	for rows.Next() {
		var i AgentKey
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.PublicKey,
			&i.Fingerprint,
			&i.EncryptedPrivateKey,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentKey = `-- name: RevokeAgentKey :exec
UPDATE agent_keys
SET status     = 'revoked',
    revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAgentKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeAgentKey, id)
	return err
}
