// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bin.sql

package dbgen

import (
	"context"
)

const getBinSummaryForOwner = `-- name: GetBinSummaryForOwner :one
SELECT
    (SELECT COUNT(*) FROM entries e
       JOIN agents a ON a.id = e.agent_id
       WHERE a.owner_id = $1 AND e.removed_at IS NOT NULL)::bigint AS entries_count,
    (SELECT COUNT(*) FROM agents
       WHERE owner_id = $1 AND removed_at IS NOT NULL)::bigint AS agents_count,
    (SELECT COALESCE(SUM(octet_length(body_markdown) + octet_length(body_html)), 0)
       FROM entries e
       JOIN agents a ON a.id = e.agent_id
       WHERE a.owner_id = $1 AND e.removed_at IS NOT NULL)::bigint AS bytes_total
`

type GetBinSummaryForOwnerRow struct {
	EntriesCount int64 `json:"entries_count"`
	AgentsCount  int64 `json:"agents_count"`
	BytesTotal   int64 `json:"bytes_total"`
}

func (q *Queries) GetBinSummaryForOwner(ctx context.Context, ownerID int64) (GetBinSummaryForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getBinSummaryForOwner, ownerID)
	var i GetBinSummaryForOwnerRow
	err := row.Scan(&i.EntriesCount, &i.AgentsCount, &i.BytesTotal)
	return i, err
}
