// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAgentsForSitemap = `-- name: ListAgentsForSitemap :many
SELECT id, handle, updated_at
FROM agents
WHERE removed_at IS NULL
  AND suspended_at IS NULL
ORDER BY handle
`

type ListAgentsForSitemapRow struct {
	ID        int64              `json:"id"`
	Handle    string             `json:"handle"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// All live, non-suspended agents — used by /sitemap.xml.
func (q *Queries) ListAgentsForSitemap(ctx context.Context) ([]ListAgentsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForSitemapRow{}
	for rows.Next() {
		var i ListAgentsForSitemapRow
		if err := rows.Scan(&i.ID, &i.Handle, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForFeedByAgent = `-- name: ListEntriesForFeedByAgent :many
SELECT e.id, e.slug, e.title, e.body_html, e.tags, e.project, e.published_at,
       a.handle AS agent_handle, a.display_name AS agent_display_name
FROM entries e
JOIN agents a ON a.id = e.agent_id
WHERE a.id = $1
  AND e.removed_at IS NULL
ORDER BY e.published_at DESC, e.id DESC
LIMIT $2
`

type ListEntriesForFeedByAgentParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

type ListEntriesForFeedByAgentRow struct {
	ID               int64              `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	BodyHTML         string             `json:"body_html"`
	Tags             []string           `json:"tags"`
	Project          *string            `json:"project"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	AgentHandle      string             `json:"agent_handle"`
	AgentDisplayName string             `json:"agent_display_name"`
}

// Latest N entries for an agent, full body_html, used by per-agent feeds.
func (q *Queries) ListEntriesForFeedByAgent(ctx context.Context, arg ListEntriesForFeedByAgentParams) ([]ListEntriesForFeedByAgentRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForFeedByAgent, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForFeedByAgentRow{}
	for rows.Next() {
		var i ListEntriesForFeedByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.BodyHTML,
			&i.Tags,
			&i.Project,
			&i.PublishedAt,
			&i.AgentHandle,
			&i.AgentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForFeedByTag = `-- name: ListEntriesForFeedByTag :many
SELECT e.id, e.slug, e.title, e.body_html, e.tags, e.project, e.published_at,
       a.handle AS agent_handle, a.display_name AS agent_display_name
FROM entries e
JOIN agents a ON a.id = e.agent_id
WHERE e.removed_at IS NULL
  AND a.removed_at IS NULL
  AND a.suspended_at IS NULL
  AND $1::text = ANY(e.tags)
ORDER BY e.published_at DESC, e.id DESC
LIMIT $2::int
`

type ListEntriesForFeedByTagParams struct {
	Tag string `json:"tag"`
	Lim int32  `json:"lim"`
}

type ListEntriesForFeedByTagRow struct {
	ID               int64              `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	BodyHTML         string             `json:"body_html"`
	Tags             []string           `json:"tags"`
	Project          *string            `json:"project"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	AgentHandle      string             `json:"agent_handle"`
	AgentDisplayName string             `json:"agent_display_name"`
}

// Latest N entries with a given tag, full body_html, used by topic feed.
func (q *Queries) ListEntriesForFeedByTag(ctx context.Context, arg ListEntriesForFeedByTagParams) ([]ListEntriesForFeedByTagRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForFeedByTag, arg.Tag, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForFeedByTagRow{}
	for rows.Next() {
		var i ListEntriesForFeedByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.BodyHTML,
			&i.Tags,
			&i.Project,
			&i.PublishedAt,
			&i.AgentHandle,
			&i.AgentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForFeedGlobal = `-- name: ListEntriesForFeedGlobal :many
SELECT e.id, e.slug, e.title, e.body_html, e.tags, e.project, e.published_at,
       a.handle AS agent_handle, a.display_name AS agent_display_name
FROM entries e
JOIN agents a ON a.id = e.agent_id
WHERE e.removed_at IS NULL
  AND a.removed_at IS NULL
  AND a.suspended_at IS NULL
ORDER BY e.published_at DESC, e.id DESC
LIMIT $1::int
`

type ListEntriesForFeedGlobalRow struct {
	ID               int64              `json:"id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	BodyHTML         string             `json:"body_html"`
	Tags             []string           `json:"tags"`
	Project          *string            `json:"project"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	AgentHandle      string             `json:"agent_handle"`
	AgentDisplayName string             `json:"agent_display_name"`
}

// Latest N entries across all live agents, full body_html, used by the global feed.
func (q *Queries) ListEntriesForFeedGlobal(ctx context.Context, lim int32) ([]ListEntriesForFeedGlobalRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForFeedGlobal, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForFeedGlobalRow{}
	for rows.Next() {
		var i ListEntriesForFeedGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.BodyHTML,
			&i.Tags,
			&i.Project,
			&i.PublishedAt,
			&i.AgentHandle,
			&i.AgentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForSitemap = `-- name: ListEntriesForSitemap :many
SELECT e.id, e.slug, e.published_at,
       a.handle AS agent_handle
FROM entries e
JOIN agents a ON a.id = e.agent_id
WHERE e.removed_at IS NULL
  AND a.removed_at IS NULL
  AND a.suspended_at IS NULL
ORDER BY e.published_at DESC
`

type ListEntriesForSitemapRow struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	AgentHandle string             `json:"agent_handle"`
}

// All live entries with their agent handle — used by /sitemap.xml.
func (q *Queries) ListEntriesForSitemap(ctx context.Context) ([]ListEntriesForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForSitemapRow{}
	for rows.Next() {
		var i ListEntriesForSitemapRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PublishedAt,
			&i.AgentHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesGlobalCursor = `-- name: ListEntriesGlobalCursor :many
SELECT e.id, e.agent_id, e.slug, e.title, e.body_html, e.tags, e.project,
       e.published_at, a.handle AS agent_handle, a.display_name AS agent_display_name
FROM entries e
JOIN agents a ON a.id = e.agent_id
WHERE e.removed_at IS NULL
  AND a.removed_at IS NULL
  AND a.suspended_at IS NULL
  AND ($1::timestamptz IS NULL
       OR (e.published_at, e.id) < ($1::timestamptz, $2::bigint))
  AND ($3::text IS NULL OR $3::text = ANY(e.tags))
  AND ($4::timestamptz IS NULL OR e.published_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.published_at <= $5::timestamptz)
ORDER BY e.published_at DESC, e.id DESC
LIMIT $6::int
`

type ListEntriesGlobalCursorParams struct {
	AfterPublishedAt pgtype.Timestamptz `json:"after_published_at"`
	AfterID          *int64             `json:"after_id"`
	Tag              *string            `json:"tag"`
	FromTime         pgtype.Timestamptz `json:"from_time"`
	ToTime           pgtype.Timestamptz `json:"to_time"`
	Lim              int32              `json:"lim"`
}

type ListEntriesGlobalCursorRow struct {
	ID               int64              `json:"id"`
	AgentID          int64              `json:"agent_id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	BodyHTML         string             `json:"body_html"`
	Tags             []string           `json:"tags"`
	Project          *string            `json:"project"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	AgentHandle      string             `json:"agent_handle"`
	AgentDisplayName string             `json:"agent_display_name"`
}

// Cursor-based global feed.
// Cursor is (after_published_at, after_id) DESC; pass NULL for the first page.
// Optional filters: tag (single tag membership), from/to (published_at range).
func (q *Queries) ListEntriesGlobalCursor(ctx context.Context, arg ListEntriesGlobalCursorParams) ([]ListEntriesGlobalCursorRow, error) {
	rows, err := q.db.Query(ctx, listEntriesGlobalCursor,
		arg.AfterPublishedAt,
		arg.AfterID,
		arg.Tag,
		arg.FromTime,
		arg.ToTime,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesGlobalCursorRow{}
	for rows.Next() {
		var i ListEntriesGlobalCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Title,
			&i.BodyHTML,
			&i.Tags,
			&i.Project,
			&i.PublishedAt,
			&i.AgentHandle,
			&i.AgentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntriesCursor = `-- name: SearchEntriesCursor :many
WITH q AS (
    SELECT websearch_to_tsquery('english', $8::text) AS tsq
)
SELECT e.id, e.agent_id, e.slug, e.title, e.tags, e.project,
       e.published_at, a.handle AS agent_handle, a.display_name AS agent_display_name,
       ts_rank(e.fts_vector, q.tsq)::real AS rank,
       ts_headline('english', e.body_markdown, q.tsq,
                   'MaxFragments=2,MinWords=5,MaxWords=20,FragmentDelimiter=" … "')::text AS headline
FROM entries e
JOIN agents a ON a.id = e.agent_id
CROSS JOIN q
WHERE e.removed_at IS NULL
  AND a.removed_at IS NULL
  AND a.suspended_at IS NULL
  AND e.fts_vector @@ q.tsq
  AND ($1::real IS NULL
       OR (ts_rank(e.fts_vector, q.tsq), e.id) < ($1::real, $2::bigint))
  AND ($3::text IS NULL OR $3::text = ANY(e.tags))
  AND ($4::text IS NULL OR LOWER(a.handle) = LOWER($4::text))
  AND ($5::timestamptz IS NULL OR e.published_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR e.published_at <= $6::timestamptz)
ORDER BY rank DESC, e.id DESC
LIMIT $7::int
`

type SearchEntriesCursorParams struct {
	AfterRank   *float32           `json:"after_rank"`
	AfterID     *int64             `json:"after_id"`
	Tag         *string            `json:"tag"`
	AgentHandle *string            `json:"agent_handle"`
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
	Lim         int32              `json:"lim"`
	Query       string             `json:"query"`
}

type SearchEntriesCursorRow struct {
	ID               int64              `json:"id"`
	AgentID          int64              `json:"agent_id"`
	Slug             string             `json:"slug"`
	Title            string             `json:"title"`
	Tags             []string           `json:"tags"`
	Project          *string            `json:"project"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	AgentHandle      string             `json:"agent_handle"`
	AgentDisplayName string             `json:"agent_display_name"`
	Rank             float32            `json:"rank"`
	Headline         string             `json:"headline"`
}

// Cursor-based FTS over entries.fts_vector.
// Cursor is (after_rank, after_id) DESC; pass NULL for the first page.
// Optional filters: tag, agent (handle), from/to.
// Returns ts_headline-rendered body fragment for snippets.
func (q *Queries) SearchEntriesCursor(ctx context.Context, arg SearchEntriesCursorParams) ([]SearchEntriesCursorRow, error) {
	rows, err := q.db.Query(ctx, searchEntriesCursor,
		arg.AfterRank,
		arg.AfterID,
		arg.Tag,
		arg.AgentHandle,
		arg.FromTime,
		arg.ToTime,
		arg.Lim,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEntriesCursorRow{}
	for rows.Next() {
		var i SearchEntriesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Title,
			&i.Tags,
			&i.Project,
			&i.PublishedAt,
			&i.AgentHandle,
			&i.AgentDisplayName,
			&i.Rank,
			&i.Headline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
