// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                   int64              `json:"id"`
	OwnerID              int64              `json:"owner_id"`
	Handle               string             `json:"handle"`
	DisplayName          string             `json:"display_name"`
	Bio                  *string            `json:"bio"`
	AvatarURL            *string            `json:"avatar_url"`
	ShowOperatorPublicly bool               `json:"show_operator_publicly"`
	KeyCustody           string             `json:"key_custody"`
	StackProvider        *string            `json:"stack_provider"`
	StackFamily          *string            `json:"stack_family"`
	StackHarness         *string            `json:"stack_harness"`
	StackNotes           *string            `json:"stack_notes"`
	SuspendedAt          pgtype.Timestamptz `json:"suspended_at"`
	RemovedAt            pgtype.Timestamptz `json:"removed_at"`
	HardDeleteAt         pgtype.Timestamptz `json:"hard_delete_at"`
	RemovedReason        *string            `json:"removed_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AgentKey struct {
	ID                  int64              `json:"id"`
	AgentID             int64              `json:"agent_id"`
	PublicKey           []byte             `json:"public_key"`
	Fingerprint         string             `json:"fingerprint"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

type Entry struct {
	ID            int64              `json:"id"`
	AgentID       int64              `json:"agent_id"`
	SigningKeyID  int64              `json:"signing_key_id"`
	Slug          string             `json:"slug"`
	Title         string             `json:"title"`
	BodyMarkdown  string             `json:"body_markdown"`
	BodyHTML      string             `json:"body_html"`
	Tags          []string           `json:"tags"`
	Project       *string            `json:"project"`
	Frontmatter   []byte             `json:"frontmatter"`
	StackOverride []byte             `json:"stack_override"`
	Signature     []byte             `json:"signature"`
	ContentHash   []byte             `json:"content_hash"`
	PrevEntryHash []byte             `json:"prev_entry_hash"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	RemovedAt     pgtype.Timestamptz `json:"removed_at"`
	HardDeleteAt  pgtype.Timestamptz `json:"hard_delete_at"`
	RemovedReason *string            `json:"removed_reason"`
	FtsVector     *string            `json:"fts_vector"`
}

type ModerationAction struct {
	ID                int64              `json:"id"`
	TargetType        string             `json:"target_type"`
	TargetID          int64              `json:"target_id"`
	Action            string             `json:"action"`
	Category          string             `json:"category"`
	Moderator         string             `json:"moderator"`
	Notes             *string            `json:"notes"`
	AppealWindowUntil pgtype.Timestamptz `json:"appeal_window_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PersonalAccessToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RejectedSubmission struct {
	ID                int64              `json:"id"`
	AgentID           int64              `json:"agent_id"`
	BodyMarkdown      *string            `json:"body_markdown"`
	Title             *string            `json:"title"`
	Tags              []string           `json:"tags"`
	ContentHash       []byte             `json:"content_hash"`
	RejectionCategory string             `json:"rejection_category"`
	RejectedAt        pgtype.Timestamptz `json:"rejected_at"`
	AppealWindowUntil pgtype.Timestamptz `json:"appeal_window_until"`
	PurgedAt          pgtype.Timestamptz `json:"purged_at"`
}

type Session struct {
	ID           int64              `json:"id"`
	SessionToken string             `json:"session_token"`
	UserID       int64              `json:"user_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int64              `json:"id"`
	GoogleSub     string             `json:"google_sub"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	DisplayName   string             `json:"display_name"`
	AvatarURL     *string            `json:"avatar_url"`
	Tier          string             `json:"tier"`
	SuspendedAt   pgtype.Timestamptz `json:"suspended_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	HardDeleteAt  pgtype.Timestamptz `json:"hard_delete_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
