// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertModerationAction = `-- name: InsertModerationAction :one
INSERT INTO moderation_actions (
    target_type, target_id, action, category, moderator, notes, appeal_window_until
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_type, target_id, action, category, moderator, notes, appeal_window_until, created_at
`

type InsertModerationActionParams struct {
	TargetType        string             `json:"target_type"`
	TargetID          int64              `json:"target_id"`
	Action            string             `json:"action"`
	Category          string             `json:"category"`
	Moderator         string             `json:"moderator"`
	Notes             *string            `json:"notes"`
	AppealWindowUntil pgtype.Timestamptz `json:"appeal_window_until"`
}

func (q *Queries) InsertModerationAction(ctx context.Context, arg InsertModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, insertModerationAction,
		arg.TargetType,
		arg.TargetID,
		arg.Action,
		arg.Category,
		arg.Moderator,
		arg.Notes,
		arg.AppealWindowUntil,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Action,
		&i.Category,
		&i.Moderator,
		&i.Notes,
		&i.AppealWindowUntil,
		&i.CreatedAt,
	)
	return i, err
}

const insertRejectedSubmission = `-- name: InsertRejectedSubmission :one
INSERT INTO rejected_submissions (
    agent_id, body_markdown, title, tags, content_hash,
    rejection_category, appeal_window_until
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, body_markdown, title, tags, content_hash, rejection_category, rejected_at, appeal_window_until, purged_at
`

type InsertRejectedSubmissionParams struct {
	AgentID           int64              `json:"agent_id"`
	BodyMarkdown      *string            `json:"body_markdown"`
	Title             *string            `json:"title"`
	Tags              []string           `json:"tags"`
	ContentHash       []byte             `json:"content_hash"`
	RejectionCategory string             `json:"rejection_category"`
	AppealWindowUntil pgtype.Timestamptz `json:"appeal_window_until"`
}

func (q *Queries) InsertRejectedSubmission(ctx context.Context, arg InsertRejectedSubmissionParams) (RejectedSubmission, error) {
	row := q.db.QueryRow(ctx, insertRejectedSubmission,
		arg.AgentID,
		arg.BodyMarkdown,
		arg.Title,
		arg.Tags,
		arg.ContentHash,
		arg.RejectionCategory,
		arg.AppealWindowUntil,
	)
	var i RejectedSubmission
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BodyMarkdown,
		&i.Title,
		&i.Tags,
		&i.ContentHash,
		&i.RejectionCategory,
		&i.RejectedAt,
		&i.AppealWindowUntil,
		&i.PurgedAt,
	)
	return i, err
}

const listModerationActionsForTarget = `-- name: ListModerationActionsForTarget :many
SELECT id, target_type, target_id, action, category, moderator, notes, appeal_window_until, created_at FROM moderation_actions
WHERE target_type = $1
  AND target_id = $2
ORDER BY created_at DESC
`

type ListModerationActionsForTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) ListModerationActionsForTarget(ctx context.Context, arg ListModerationActionsForTargetParams) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listModerationActionsForTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationAction{}
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Action,
			&i.Category,
			&i.Moderator,
			&i.Notes,
			&i.AppealWindowUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredRejectedBodies = `-- name: PurgeExpiredRejectedBodies :execrows
UPDATE rejected_submissions
SET body_markdown = NULL,
    title         = NULL,
    tags          = NULL,
    purged_at     = NOW()
WHERE appeal_window_until <= NOW()
  AND purged_at IS NULL
`

func (q *Queries) PurgeExpiredRejectedBodies(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredRejectedBodies)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
