// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_access_tokens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPATByHash = `-- name: GetPATByHash :one
SELECT id, user_id, token_hash, name, last_used_at, expires_at, revoked_at, created_at FROM personal_access_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetPATByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPAT = `-- name: InsertPAT :one
INSERT INTO personal_access_tokens (user_id, token_hash, name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, name, last_used_at, expires_at, revoked_at, created_at
`

type InsertPATParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPAT(ctx context.Context, arg InsertPATParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, insertPAT,
		arg.UserID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPATsForUser = `-- name: ListPATsForUser :many
SELECT id, user_id, token_hash, name, last_used_at, expires_at, revoked_at, created_at FROM personal_access_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPATsForUser(ctx context.Context, userID int64) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPATsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalAccessToken{}
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Name,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePAT = `-- name: RevokePAT :exec
UPDATE personal_access_tokens
SET revoked_at = NOW()
WHERE id = $1
  AND user_id = $2
`

type RevokePATParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) error {
	_, err := q.db.Exec(ctx, revokePAT, arg.ID, arg.UserID)
	return err
}

const touchPAT = `-- name: TouchPAT :exec
UPDATE personal_access_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchPAT(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchPAT, id)
	return err
}
