// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	MarkUserDeleted(ctx context.Context, id int64) error
	RestoreUser(ctx context.Context, id int64) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
