// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_sub, email, email_verified, display_name, avatar_url, tier, suspended_at, deleted_at, hard_delete_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarURL,
		&i.Tier,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.HardDeleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, google_sub, email, email_verified, display_name, avatar_url, tier, suspended_at, deleted_at, hard_delete_at, created_at, updated_at FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarURL,
		&i.Tier,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.HardDeleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, email_verified, display_name, avatar_url, tier, suspended_at, deleted_at, hard_delete_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarURL,
		&i.Tier,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.HardDeleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (google_sub, email, email_verified, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, google_sub, email, email_verified, display_name, avatar_url, tier, suspended_at, deleted_at, hard_delete_at, created_at, updated_at
`

type InsertUserParams struct {
	GoogleSub     string  `json:"google_sub"`
	Email         string  `json:"email"`
	EmailVerified bool    `json:"email_verified"`
	DisplayName   string  `json:"display_name"`
	AvatarURL     *string `json:"avatar_url"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.GoogleSub,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.AvatarURL,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarURL,
		&i.Tier,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.HardDeleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserDeleted = `-- name: MarkUserDeleted :exec
UPDATE users
SET deleted_at     = NOW(),
    hard_delete_at = NOW() + INTERVAL '30 days',
    updated_at     = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserDeleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUserDeleted, id)
	return err
}

const purgeExpiredUsers = `-- name: PurgeExpiredUsers :execrows
DELETE FROM users
WHERE hard_delete_at IS NOT NULL
  AND hard_delete_at <= NOW()
`

func (q *Queries) PurgeExpiredUsers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredUsers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at     = NULL,
    hard_delete_at = NULL,
    updated_at     = NOW()
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    avatar_url   = $3,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, google_sub, email, email_verified, display_name, avatar_url, tier, suspended_at, deleted_at, hard_delete_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          int64   `json:"id"`
	DisplayName string  `json:"display_name"`
	AvatarURL   *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.AvatarURL)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarURL,
		&i.Tier,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.HardDeleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
